#
# 资产
#

id = 10022
name = { Cn = "资产", En = "assets" }

# 数据描写 或者 模式
schema = [
    # 通用属性
    # common
    { id = 1000, data_type = "String", name = { Cn = "编号", En = "id"}, removed = false },
    { id = 1001, data_type = "String", name = { Cn = "实体名", En = "name"}, removed = false },
    { id = 1002, data_type = "String", name = { Cn = "创建人", En = "creator"}, removed = false },
    { id = 1003, data_type = "Int64", name = { Cn = "创建时间戳", En = "create_timestamp"}, removed = false },
    { id = 1004, data_type = "String", name = { Cn = "修改人", En = "modifier"}, removed = false },
    { id = 1005, data_type = "Int64", name = { Cn = "修改时间戳", En = "modify_timestamp"}, removed = false },
    { id = 1006, data_type = "String", name = { Cn = "主人", En = "owner"}, removed = false },
    { id = 1007, data_type = "String", name = { Cn = "组表", En = "groups"}, removed = false },
    { id = 1008, data_type = "List", name = { Cn = "数据", En = "datas"}, removed = false },
    #-----------------
    # 专有属性
    #-----------------
    { id = 2008, data_type = "String", name = { Cn = "根路径", En = "root"}, removed = false },
    { id = 2009, data_type = "List", name = { Cn = "原始库", En = "origin_library"}, removed = false },
    { id = 2010, data_type = "Map", name = { Cn = "变体", En = "variants"}, removed = false },
]

# 特有属性

# 事件队列和消息队列表
[queues]

# 事件定义, 不是必须
[events]
event_queue = []
massage_queue = []

# 初始实体
[items]


[view_rules]

[view_rules.manage]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }
[view_rules.entity]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }

[view_rules.schema.1000]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1001]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1002]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1003]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1004]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1005]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1006]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1007]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1008]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1009]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.10010]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }