#
# 集
#

id = 20008
name_map = { zh = "预组件", en = "assemblies" }

# 数据描写 或者 模式
schema = [
    { data_type = "String", name_map = { zh = "原始集", en = "original_collection"}, removed = false },
    { data_type = "List", name_map = { zh = "关联集", en = "associated_collections"}, removed = false },
    { data_type = "List", name_map = { zh = "引用表", en = "references"}, removed = false },

    # done, suspending, cancal
    { data_type = "String", name_map = { zh = "状态", en = "status"}, removed = false },
    { data_type = "List", name_map = { zh = "预览", en = "previews"}, removed = false },
]

# 特有属性

# 事件队列和消息队列表
[queues]

# 事件定义, 不是必须
[events]
event_queue = []
massage_queue = []

# 初始实体
[items]


[view_rules]

[view_rules.manage]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
[view_rules.collection]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "OwnerWrite", read_filters = [
    "OnlyOwner",
], write_filters = [
] }

[view_rules.schema.1000]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1001]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1002]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1003]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1004]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1005]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1006]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1007]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1008]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1009]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1010]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }
[view_rules.schema.1011]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
    "NoLimit",
], write_filters = [
] }

[view_rules.schema.2001]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.2002]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.2003]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
    "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
